### ISSUE TITLE
Vignette fix

### ISSUE THREAD

**Issue by TomG007** [TomG007/rHFA#1]
rHFA Guide line 300:

`r round(pophfa$home_field[1, 1]/mean(corn$YIELD), 3)*100`% increase over

This inline statement throws an error:
Error in pophfa$home_field[1, 1] : incorrect number of dimensions

**Comment by PatrickEwing-USDA** [comment]
Found this one. When the magrittr pipes were purged, magrittr::set_rownames(x, value) was changed to rownames(x, value), instead of rownames(x) <- value. in permute_hfa().

**Comment by TomG007** [comment]
Fixed by Patrick
