### ISSUE TITLE
Install rHFA from github repo - vignette

### ISSUE THREAD

**Issue by TomG007** [TomG007/rHFA#9]
To build rHFA directly from the repo, this command works:

`> remotes::install_github("TomG007/rHFA", build_vignettes = TRUE, force = TRUE)`

Should we include a note in README, or not worry about it because users should find it on CRAN?

**Comment by kant0063** [comment]
yes I think we should

**Comment by TomG007** [comment]
Added this to the **Brief how-to:** section
The rHFA Guide vignette contains a step-by-step analysis of sample data. When installing the package from github, use this command to ensure the vignette is included.

`> remotes::install_github("PatrickEwing-USDA/rHFA", build_vignettes = TRUE)`
